name: End to end integration tests for iOS App

on:
  push:
#    branches:
#      - main

jobs:
  e2e-ios:
    runs-on: macos-14
    steps:
      - name: ⬇️ Check out repository code
        uses: actions/checkout@v4

      # XCode and NPM already installed. See full list of preinstalled software here:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

      - name: Build iOS app
        working-directory: ./ios
        run: xcodebuild build -workspace "Runner.xcworkspace" -scheme "Runner" -destination "platform=iOS Simulator,name=iPhone 15" -configuration Debug -derivedDataPath ../appium/apps -sdk iphonesimulator17.2

      - name: Create appium/apps directory
        working-directory: ./appium
        run: mkdir apps

      - name: Move Runner.app to base dir
        working-directory: ./appium/apps
        run: mv ./Build/Products/Debug-iphonesimulator/Runner.app .

      - name: 📦 Install Appium
        run: npm i -g appium

      - name: Install iOS appium driver
        run: appium driver install xcuitest

      - name: Create report directory
        working-directory: ./appium
        run: mkdir -p reports/screenshots

      - name: Run tests
        working-directory: ./appium
        run: npm run ios.app

      - name: Zip report
        working-directory: ./appium
        run: zip -r reports.zip reports

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports.zip